---

- name: "3.5.3.1.1 | L1 | PATCH | Ensure iptables packages are installed"
  package:
      name: "{{ item }}"
      state: present
  loop:
      - iptables
      - iptables-services
  vars:
      ansible_python_interpreter: /bin/python
  when:
      - "'iptables' not in ansible_facts.packages"
      - rhel7cis_rule_3_5_3_1_1
  tags:
      - level1
      - patch
      - rule_3.5.3.1

- name: "3.5.3.1.2 | L1 | PATCH | Ensure nftables is not installed with iptables"
  package:
      name: nftables
      state: absent
  vars:
      ansible_python_interpreter: /bin/python
  when:
      - "'nftables' in ansible_facts.packages"
      - rhel7cis_rule_3_5_3_1_2
  tags:
      - level1
      - patch
      - rule_3.5.3.2

- name: "3.5.3.1.3 | L1 | PATCH | Ensure firewalld is either not installed or masked with iptables"
  package:
      name: firewalld
      state: absent
  vars:
      ansible_python_interpreter: /bin/python
  when:
      - "'firewalld' in ansible_facts.packages"
      - rhel7cis_rule_3_5_3_1_3
  tags:
      - level1
      - patch
      - rule_3.5.3.3
