---
# This playbook is ONLY to be used when updating config files on agent machines. 
# REMEMBER TO ADD ALL IP ADDRS TO /etc/ansible/hosts
- hosts: all
  become: yes
  become_user: root
  tasks: 
  - name: Copy osquery.conf to remote system
    copy:
      src: "ansible-wazuh-agent/files/osquery.conf"
      dest: /etc/osquery/osquery.conf

  - name: Restart service osqueryd, in all cases
    service:
      name: osqueryd
      state: restarted
