---
# This playbook is ONLY to be used when updating config files on agent machines. 
# REMEMBER TO ADD ALL IP ADDRS TO /etc/ansible/hosts
- hosts: all
  become: yes
  become_user: root
  tasks: 
  - name: Copy osquery.conf to agents
    copy:
      src: "ansible-wazuh-agent/files/osquery.conf"
      dest: /etc/osquery/osquery.conf

  - name: Restart service osqueryd
    service:
      name: osqueryd
      state: restarted

  tasks: 
  - name: Copy audit.rules to agents
    copy:
      src: "ansible-wazuh-agent/files/audit.rules"
      dest: /etc/audit/audit.rules

  - name: Reload rules
    shell: "auditctl -R /etc/audit/audit.rules"

- name: restart wazuh-agent
  service: name=wazuh-agent state=restarted enabled=yes

# you can reload using auditctl -l but it's kinda pointless to put this in the script bc you won't see the output
