---
- name: Stop webmin
  hosts: machines  # Replace with actual hosts hame
  remote_user: root 

  # Running with no arguments runs both procedures
  tasks:
  - name: Stop webmin service
    ansible.builtin.service:  # Successfully stops on Debian
      name: webmin
      state: stopped
    tags: stop
  - name: Uninstall webmin
    ansible.builtin.package:  # Will not uninstall for some reason
      name: webmin 
      state: absent
    tags: rm
...
