---
- name: Stop webmin
  hosts: machines  # Replace with actual hosts hame
  remote_user: root 

  # Running with no arguments runs both procedures
  tasks:
  - name: Stop webmin service
    ansible.builtin.service:  # Tested successfully on Debian with systemctl
      name: webmin
      state: stopped
    tags: stop
  - name: Uninstall webmin
    ansible.builtin.package: # may still appear in systemctl as masked 
      name: webmin 
      state: absent
    tags: rm
...
