---
- hosts: /etc/ansible/hosts
  become: yes
  become_user: root
  roles:
    - ./ansible-wazuh-agent
  vars:
    DEB: 
    wazuh_managers:
      - address: <MANAGER_IP>
        port: 1514
        protocol: tcp
        api_port: 55000
        api_proto: 'http'
        api_user: ansible
        max_retries: 5
        retry_interval: 5
    wazuh_agent_authd:
        registration_address: <MANAGER_IP>
        enable: true
        port: 1515
        ssl_agent_ca: null
        ssl_auto_negotiate: 'no'
