---
# Install OSQuery and Wazuh to debian machines
  - name: set package files to install
    set_fact:
        DEB:
          - osquery_5.5.1-1.linux_amd64.deb
          - wazuh-agent_4.3.9-1_debian_amd64.deb

- name: Debian/Ubuntu | Install apt-transport-https, ca-certificates and acl
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - acl
    state: present
  register: wazuh_agent_ca_package_install
  until: wazuh_agent_ca_package_install is succeeded

  - name: Make Directory
    file:
      path: /var/ansible
      state: directory
  - name: Copy files to remote system
    copy:
      src: "packages/Debian/{{ item }}"
      dest: /var/ansible/
    loop: "{{ DEB }}"
  - name: Install the files in that path
    command: "dpkg -i /var/ansible/{{ item }}"
    loop: "{{ DEB }}"
