---
# Install OSQuery and Wazuh to debian machines
- hosts: all
  vars:
    DEB: 
      - osquery_5.1.0-1.linux.amd64.deb
      - wazuh-agent_4.2.5-1_amd64.deb
  tasks:
  - name: Make Directory
    file:
      path: /var/ansible
      state: directory
  - name: Copy files to remote system
    copy:
      src: "{{ item }}"
      dest: /var/ansible/
    loop: "{{ DEB }}"
  - name: Install the files in that path
    command: "dpkg -i /var/ansible/{{ item }}"
    loop: "{{ DEB }}"
