---

- name: Get latest Wazuh release
  become: false
  shell: "curl --silent https://api.github.com/repos/wazuh/wazuh/releases/latest | grep '\"tag_name\":' | sed -E 's/.*\"([^\"]+)\".*/\\1/'| cut -c 2-"
  register: wazuh_latest_release
  delegate_to: localhost

- include_vars: ../../vars/repo.yml
  when: "wazuh_latest_release.stdout is version(wazuh_agent_version, operator='ge')"

- include_vars: ../../vars/repo_dev.yml
  when: "wazuh_latest_release.stdout is version(wazuh_agent_version, operator='lt')"

- name: Overlay wazuh_agent_config on top of defaults
  set_fact:
    wazuh_agent_config: '{{ wazuh_agent_config_defaults | combine(config_layer, recursive=True) }}'
  vars:
    config_layer: '{{ wazuh_agent_config | default({}) }}'
  when: wazuh_agent_config_overlay | bool

- include_tasks: "Windows.yml"
  when: ansible_os_family == "Windows"

- include_tasks: "Linux.yml"
  when: ansible_system == "Linux"
