---
  - name: Copy osquery.conf to remote system
    when: osquery_install is succeeded
    tags: copy-conf
    copy:
      src: "files/osquery.conf"
      dest: /etc/osquery/osquery.conf

  - name: Restart service osqueryd, in all cases
    when: osquery_install is succeeded
    tags: copy-conf
    service:
      name: osqueryd
      state: restarted
