---
- hosts: all
  tasks:
    - name: Get a list of users
      shell: 'cut -d: -f1 /etc/passwd'
      changed_when: false
      register: existing_users   

    - name: Echo passwords in CSV format for input into password manager
      delegate_to: localhost
      lineinfile:
        line: "{{ inventory_hostname }},{{ item }},{{ lookup('password', 'credentials/' + inventory_hostname + '/' + item) }}"
        insertafter: EOF
        dest: /root/Passwords-For-{{ inventory_hostname }}.csv
        create: yes
      loop:
        "{{ existing_users.stdout_lines }}"

    - name: Change user password
      user:
        name: "{{ item }}"
        update_password: always
        password: "{{ lookup('password', 'credentials/' + inventory_hostname + '/' + item)|password_hash('sha512') }}"
      loop:
        "{{ existing_users.stdout_lines }}"
