---
- name: "MANUAL | 2.3 | AUDIT | Ensure nonessential services are removed or masked"
  block:
      - name: "MANUAL | 2.3 | AUDIT | Ensure nonessential services are removed or masked | Check for services"
        shell: lsof -i -P -n | grep -v "(ESTABLISHED)"
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu20cis_2_3_services

      - name: "MANUAL | 2.3 | AUDIT | Ensure nonessential services are removed or masked | Message out running services"
        debug:
            msg:
                - "Warning!! Below are the running services. Please review and remove as well as mask un-needed services"
                - "{{ ubtu20cis_2_3_services.stdout_lines }}"
  when:
      - ubtu20cis_rule_2_3
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_2.3
      - services
