---
- hosts: all
  become: true
  vars:
      is_container: false

  roles:

      - role: "{{ playbook_dir }}"
        ubtu20cis_system_is_container: "{{ is_container | default(false) }}"
        ubtu20cis_skip_for_travis: false
        ubtu20cis_oscap_scan: yes
