- name: Run Audit Script on Inventory Hosts
  hosts: all
  become: true
  vars:
    op: "{{ operation }}"
    wazuhManager: "{{ WAZUH_MANAGER }}" 
    aptPackages: "sudo nmap tmux vim hostname htop clamav lynis debsums"
    otherPackages: "sudo nmap tmux vim hostname htop clamav lynis"
    DEB: 
      - osquery_4.5.1_1.linux.amd64.deb
      - wazuh-agent_4.2.4-1_amd64.deb
  tasks:
    # install packages
    - include: ./packageInstallations/aptPackage.yml
      when: op == "i" and ansible_pkg_mgr == 'apt'
    - include: ./packageInstallations/yumPackage.yml
      when: op == "i" and ansible_pkg_mgr == 'yum'
    - include: ./packageInstallations/pacmanPackage.yml
      when: op == "i" and ansible_pkg_mgr == 'pacman'
    - include: ./packageInstallations/apkPackage.yml
      when: op == "i" and ansible_pkg_mgr == 'apk'

    # install monitoring
    - include: ./monitoringInstallations/aptPackage.yml
      when: op == "m" and ansible_pkg_mgr == 'apt'

    - name: Display help
      script: ../audit.sh -h
      when: op == "h"

    - debug: msg="{{ output }}"