---
- name: "SCORED | 6.7 | PATCH | Ensure FIPS 140-2 OpenSSL Cryptography Is Used | PostgreSQL must implement NIST FIPS 140-2 validated cryptographic modules to generate and validate cryptographic hashes (RHEL7)."
  block:
      - name: "SCORED | 6.7 | PATCH | Ensure FIPS 140-2 OpenSSL Cryptography Is Used | PostgreSQL must implement NIST FIPS 140-2 validated cryptographic modules to generate and validate cryptographic hashes (RHEL7)."
        yum:
            name: dracut-fips
            state: present
        notify: rebuild initramfs

      - name: "SCORED | 6.7 | AUDIT | Ensure FIPS 140-2 OpenSSL Cryptography Is Used| Check if prelink package is installed"
        command: rpm -q prelink
        args:
            warn: no
        changed_when: no
        failed_when: no
        check_mode: no
        register: pgs12CIS_6_7_prelink_installed

      - name: "SCORED | 6.7 | PATCH | Ensure FIPS 140-2 OpenSSL Cryptography Is Used| Disable prelinking."
        lineinfile:
            dest: /etc/sysconfig/prelink
            regexp: ^#?PRELINKING
            line: PRELINKING=no
        when: pgs12CIS_6_7_prelink_installed.rc == 0
        notify: undo existing prelinking

      - name: "SCORED | 6.7 | AUDIT | Ensure FIPS 140-2 OpenSSL Cryptography Is Used | Check for GRUB_CMDLINE_LINUX in /etc/default/grub"
        command: grep -P '^\s*GRUB_CMDLINE_LINUX=".*"$' /etc/default/grub
        check_mode: no
        failed_when: no
        changed_when: pgs12cis_6_7_default_grub_missing_audit.rc > 0
        register: pgs12cis_6_7_default_grub_missing_audit

      - name: "SCORED | 6.7 | AUDIT | Ensure FIPS 140-2 OpenSSL Cryptography Is Used | parse sane GRUB_CMDLINE_LINUX from /proc/cmdline"
        command: grep -oP ' ro \K.*?(?= ?LANG=)' /proc/cmdline
        check_mode: no
        changed_when: no
        failed_when: pgs12cis_grub_cmdline_linux_audit.rc > 1
        when: pgs12cis_6_7_default_grub_missing_audit is changed
        register: pgs12cis_grub_cmdline_linux_audit

      - name: "SCORED | 6.7 | PATCH | Ensure FIPS 140-2 OpenSSL Cryptography Is Used | Copy over a sane /etc/default/grub"
        template:
            src: etc_default_grub.j2
            dest: /etc/default/grub
            owner: root
            group: root
            mode: 0644
        vars:
            grub_cmdline_linux: "{{ pgs12cis_grub_cmdline_linux_audit.stdout }}"
        when: pgs12cis_grub_cmdline_linux_audit is changed

      - name: "SCORED | 6.7 | PATCH | Ensure FIPS 140-2 OpenSSL Cryptography Is Used | fips=1 must be in /etc/default/grub"
        replace:
            path: /etc/default/grub
            regexp: "{{ pgs12cis_regexp_quoted_params }}"
            replace: "{{ pgs12cis_replace_quoted_params }}"
        vars:
            key: GRUB_CMDLINE_LINUX
            param: fips
            value: 1
            append: yes  # this is the default
        when:
            - not ansible_check_mode or
              pgs12cis_6_7_default_grub_missing_audit is not changed
        notify: make grub2 config

      - name: "SCORED | 6.7 | PATCH | Ensure FIPS 140-2 OpenSSL Cryptography Is Used | If /boot or /boot/efi reside on separate partitions, the kernel parameter boot=<partition> must be added to the kernel command line."
        replace:
            path: /etc/default/grub
            regexp: "{{ pgs12cis_regexp_quoted_params }}"
            replace: "{{ pgs12cis_replace_quoted_params }}"
        with_items:
            - "{{ ansible_mounts | json_query(query) }}"
        vars:
            query: "[?mount=='{{ pgs12cis_boot_part }}'] | [0]"
            key: GRUB_CMDLINE_LINUX
            param: boot
            value: UUID={{ item.uuid }}
            insert: yes
        when:
            - pgs12cis_boot_part not in ['/', '']
            - not ansible_check_mode or
              pgs12cis_6_7_default_grub_missing_audit is not changed
        notify: make grub2 config
        register: result

      - name: "SCORED | 6.7 | AUDIT | Ensure FIPS 140-2 OpenSSL Cryptography Is Used | Verify kernel parameters in /etc/default/grub"
        command: grep -P '^\s*GRUB_CMDLINE_LINUX=".*(?<=[" ]){{ item | regex_escape }}(?=[" ]).*"$' /etc/default/grub
        check_mode: no
        with_items:
            - fips=1
            - boot=UUID={{ ansible_mounts | json_query(query) }}
        vars:
            query: "[?mount=='{{ pgs12cis_boot_part }}'].uuid | [0]"
        register: pgs12cis_6_7_audit
        when:
            - not ansible_check_mode or
              pgs12cis_6_7_default_grub_missing_audit is not changed
            - pgs12cis_boot_part not in ['/', ''] or
              'boot=' not in item
        changed_when:
            - ansible_check_mode
            - pgs12cis_6_7_audit is failed
        failed_when:
            - pgs12cis_6_7_audit is failed
            - not ansible_check_mode or
              pgs12cis_6_7_audit.rc > 1
